#!/bin/sh

WC='\033[0;33m' # Orange
EN='\033[0m' # No Color

dirty=false;
count=0;
arr=();

for i in {0..9}; do
	arr+=(false);
done

while read st file; do
	for i in {0..9}; do
		if [[ $file == *"level-${i}"* ]]; then
			arr[$i]=true;
		fi
	done

	if [[ $file != *"level-"* ]]; then
		arr[0]=true;
	fi
done <<< "$(git diff --cached --name-status)"

for i in "${arr[@]}"; do
	if [[ $i = true ]]; then
		count=$((count + 1));
	fi

	if [[ $count > 1 ]]; then
		dirty=true;
	fi
done

if [[ $dirty = true ]]; then
	echo "";
	echo "${WC}Dirty commmit${EN} - detected changes to multiple levels";
	echo "";
	
	for i in "${!arr[@]}"; do
		if [[ ${arr[$i]} = true ]]; then
			echo "Changes to \033[0;3$(($i + 1))mlevel-${i}${EN}";
		fi
	done

	echo "";
	echo "Please separate files from each level into separate commits";
	echo "If you are sure this commit is fine then you can bypass this check with the ${WC}--no-verify${EN} flag"
	echo "";
	exit 1;
fi